version: '3.8'
services:
  dynamodb-local:
    container_name: dynamodb-local
    image: 'amazon/dynamodb-local:latest'
    command: '-jar DynamoDBLocal.jar -sharedDb -inMemory'
    ports:
      - '8000:8000'
    healthcheck:
      test: ['CMD', 'curl', 'http://localhost:8000']
      interval: 1s
      timeout: 10s
      retries: 5

  dynamodb-admin:
    container_name: dynamodb-admin
    image: aaronshaf/dynamodb-admin
    environment:
      DYNAMO_ENDPOINT: 'http://dynamodb-local:8000'
      AWS_REGION: 'local'
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local
    ports:
      - '8001:8001'
    depends_on:
      - dynamodb-local

  dynamodb-local-init:
    container_name: dynamodb-local-init
    image: amazon/aws-cli
    environment:
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local
    command: >-
      dynamodb create-table
          --table-name products
          --attribute-definitions
              AttributeName=PK,AttributeType=S
              AttributeName=SK,AttributeType=S
          --key-schema
              AttributeName=PK,KeyType=HASH
              AttributeName=SK,KeyType=RANGE
          --billing-mode PAY_PER_REQUEST
          --endpoint-url http://dynamodb-local:8000 --region local
    depends_on:
      dynamodb-local:
        condition: service_healthy
